-- InvoiceFlow PostgreSQL schema (translated from SQLite inventory in src/lib/db.ts).
-- Idempotent: safe to run on every boot via CREATE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  company_name TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  role TEXT NOT NULL DEFAULT 'admin',
  owner_user_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  company_name TEXT,
  email TEXT,
  phone TEXT,
  address TEXT,
  ordered TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  invoice_number TEXT NOT NULL,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'paid', 'overdue')),
  issue_date TEXT NOT NULL,
  due_date TEXT NOT NULL,
  tax_rate DOUBLE PRECISION DEFAULT 0,
  notes TEXT,
  terms TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  order_id INTEGER,
  quotation_id INTEGER,
  last_reminder_at TEXT,
  last_due_soon_reminder_at TEXT,
  source_platform TEXT NOT NULL DEFAULT 'manual',
  original_order_id TEXT,
  system_order_no TEXT,
  external_invoice_number TEXT,
  billing_address TEXT,
  shipping_address TEXT,
  email TEXT,
  send_later INTEGER NOT NULL DEFAULT 0,
  ship_via TEXT,
  shipping_date TEXT,
  tracking_no TEXT,
  order_no TEXT,
  receipt_date TEXT,
  currency TEXT DEFAULT 'HKD',
  discount_type TEXT DEFAULT 'percent',
  discount_value DOUBLE PRECISION DEFAULT 0,
  shipping_amount DOUBLE PRECISION DEFAULT 0,
  term TEXT DEFAULT 'NET30',
  deposit_amount DOUBLE PRECISION,
  thumbnail_file_id INTEGER,
  UNIQUE (user_id, invoice_number)
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
  unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  product_service TEXT,
  class_name TEXT
);

CREATE TABLE IF NOT EXISTS invoice_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  path TEXT NOT NULL,
  original_name TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS expenses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category TEXT NOT NULL DEFAULT 'other',
  merchant TEXT,
  amount_hkd DOUBLE PRECISION,
  amount_rmb DOUBLE PRECISION,
  paid_date TEXT,
  order_no TEXT,
  platform TEXT,
  notes TEXT,
  payment_status TEXT DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid', 'pending', 'paid')),
  receipt_path TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  receipt_no TEXT,
  batch_id TEXT,
  payment_method TEXT,
  created_by_user_id INTEGER REFERENCES users(id),
  special_notes TEXT,
  supplier_input TEXT,
  payment_channel TEXT,
  funding_source TEXT,
  card_last4 TEXT
);

CREATE TABLE IF NOT EXISTS expense_receipts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_id INTEGER NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  path TEXT NOT NULL,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  source_url TEXT
);

CREATE TABLE IF NOT EXISTS expense_options (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  value TEXT NOT NULL,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (user_id, type, value)
);

CREATE TABLE IF NOT EXISTS expense_option_settings (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  db_authoritative INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, type)
);

CREATE TABLE IF NOT EXISTS expense_report_sequence (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  next_serial INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS global_record_sequences (
  record_type TEXT PRIMARY KEY CHECK (record_type IN ('order', 'quotation', 'invoice')),
  next_serial INTEGER NOT NULL DEFAULT 1 CHECK (next_serial > 0)
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  po_number TEXT,
  name TEXT,
  description TEXT,
  status TEXT DEFAULT 'OPEN',
  delivery_date TEXT,
  customer_email TEXT,
  phone TEXT,
  shipping_address TEXT,
  notes TEXT,
  fields_json TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  carton_count TEXT,
  quotation_id INTEGER,
  source_platform TEXT NOT NULL DEFAULT 'manual',
  original_order_id TEXT,
  system_order_no TEXT,
  reference_number TEXT,
  total_amount DOUBLE PRECISION,
  order_type TEXT,
  attended_at TEXT
);

CREATE TABLE IF NOT EXISTS order_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  path TEXT NOT NULL,
  original_name TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS activity_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL DEFAULT 'comment',
  author TEXT,
  body TEXT NOT NULL,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS quotations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL,
  quote_number TEXT NOT NULL,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'approved', 'rejected')),
  issue_date TEXT NOT NULL,
  valid_until TEXT,
  tax_rate DOUBLE PRECISION DEFAULT 0,
  notes TEXT,
  terms TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  billing_address TEXT,
  shipping_address TEXT,
  email TEXT,
  send_later INTEGER NOT NULL DEFAULT 0,
  ship_via TEXT,
  shipping_date TEXT,
  tracking_no TEXT,
  order_no TEXT,
  receipt_date TEXT,
  currency TEXT DEFAULT 'HKD',
  discount_type TEXT DEFAULT 'percent',
  discount_value DOUBLE PRECISION DEFAULT 0,
  shipping_amount DOUBLE PRECISION DEFAULT 0,
  thumbnail_file_id INTEGER
);

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS external_invoice_number TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS quotation_id INTEGER;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS deposit_amount DOUBLE PRECISION;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS thumbnail_file_id INTEGER;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS thumbnail_file_id INTEGER;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS reference_number TEXT;

CREATE TABLE IF NOT EXISTS quotation_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_id INTEGER NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
  unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  product_service TEXT,
  class_name TEXT
);

CREATE TABLE IF NOT EXISTS quotation_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_id INTEGER NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  path TEXT NOT NULL,
  original_name TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS other_income (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category TEXT,
  txn_date TEXT,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  account TEXT,
  remarks TEXT,
  receipt_path TEXT,
  verified INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS kitchen_finished (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  sku TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  UNIQUE (user_id, sku)
);

CREATE TABLE IF NOT EXISTS kitchen_raw (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  unit TEXT,
  total_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
  allocated_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
  UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS kitchen_gift_boxes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  box_type TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  UNIQUE (user_id, box_type)
);

CREATE TABLE IF NOT EXISTS kitchen_movements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  details_json TEXT NOT NULL DEFAULT '{}',
  order_id INTEGER REFERENCES orders(id) ON DELETE SET NULL,
  created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  voided_at TEXT,
  voided_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  voids_movement_id INTEGER
);

CREATE TABLE IF NOT EXISTS kitchen_order_fulfillments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  need_key TEXT NOT NULL,
  fulfilled_qty INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (user_id, order_id, need_key)
);

CREATE TABLE IF NOT EXISTS kitchen_prep_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  order_code TEXT NOT NULL,
  linked_order_id INTEGER REFERENCES orders(id) ON DELETE SET NULL,
  stewing_date TEXT NOT NULL,
  order_type TEXT NOT NULL DEFAULT 'daily' CHECK (order_type IN ('daily', 'wedding', 'restock')),
  capacity TEXT NOT NULL DEFAULT '45g',
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('not_started', 'scheduled', 'prepped', 'stewing', 'completed')),
  qty_osmanthus INTEGER NOT NULL DEFAULT 0,
  qty_red_date INTEGER NOT NULL DEFAULT 0,
  qty_rock_sugar INTEGER NOT NULL DEFAULT 0,
  actual_qty_osmanthus INTEGER,
  actual_qty_red_date INTEGER,
  actual_qty_rock_sugar INTEGER,
  bird_nest_osmanthus TEXT DEFAULT 'large',
  bird_nest_red_date TEXT DEFAULT 'large',
  bird_nest_rock_sugar TEXT DEFAULT 'large',
  notes TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  expected_yield INTEGER,
  actual_yield INTEGER,
  completion_remarks TEXT,
  completed_at TEXT,
  completed_by TEXT,
  stewing_started_at TEXT,
  completion_splits_json TEXT
);

CREATE TABLE IF NOT EXISTS kitchen_settings (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  holiday_mode INTEGER NOT NULL DEFAULT 0,
  catalog_json TEXT,
  formulas_json TEXT,
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS stock_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  current_qty DOUBLE PRECISION NOT NULL DEFAULT 0,
  safety_qty DOUBLE PRECISION NOT NULL DEFAULT 0,
  icon_path TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (user_id, category, name)
);

ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS icon_path TEXT;

ALTER TABLE kitchen_settings ADD COLUMN IF NOT EXISTS catalog_json TEXT;
ALTER TABLE kitchen_settings ADD COLUMN IF NOT EXISTS formulas_json TEXT;
ALTER TABLE kitchen_settings ADD COLUMN IF NOT EXISTS catalog_merge_version TEXT;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_type TEXT;

CREATE TABLE IF NOT EXISTS inbound_shipments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  waybill_number TEXT,
  sender TEXT,
  sender_address TEXT,
  receiver_address TEXT,
  arrival_date TEXT,
  amount DOUBLE PRECISION,
  photo_path TEXT,
  notes TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

ALTER TABLE inbound_shipments ADD COLUMN IF NOT EXISTS sender_address TEXT;
ALTER TABLE inbound_shipments ADD COLUMN IF NOT EXISTS receiver_address TEXT;
ALTER TABLE inbound_shipments ADD COLUMN IF NOT EXISTS amount DOUBLE PRECISION;

-- Org-wide inbound: child-user rows belong to the admin data pool.
UPDATE inbound_shipments s
SET user_id = u.owner_user_id
FROM users u
WHERE s.user_id = u.id
  AND u.owner_user_id IS NOT NULL
  AND s.user_id <> u.owner_user_id;

-- rental_tenants before rental_units (units.tenant_id FK)
CREATE TABLE IF NOT EXISTS rental_tenants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  contact_name TEXT,
  company_name TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  notes TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  utility_billing_mode TEXT NOT NULL DEFAULT 'company_proxy'
);

CREATE TABLE IF NOT EXISTS rental_units (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  unit_name TEXT NOT NULL,
  tenant_name TEXT NOT NULL,
  tenant_contact_name TEXT,
  tenant_company_name TEXT,
  tenant_notes TEXT,
  tenant_phone TEXT,
  tenant_email TEXT,
  tenant_address TEXT,
  current_year_rent DOUBLE PRECISION NOT NULL DEFAULT 0,
  previous_years_rent_json TEXT DEFAULT '[]',
  lease_start_date TEXT,
  lease_end_date TEXT,
  due_date_day INTEGER NOT NULL DEFAULT 1,
  auto_send_receipt_email INTEGER NOT NULL DEFAULT 0,
  automation_enabled INTEGER NOT NULL DEFAULT 1,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  tenant_id INTEGER REFERENCES rental_tenants(id),
  utility_billing_mode TEXT NOT NULL DEFAULT 'company_proxy',
  address TEXT,
  billing_company TEXT,
  current_lease_id INTEGER,
  shared_meter_deduction_unit_ids_json TEXT DEFAULT '[]'
);

ALTER TABLE rental_units ADD COLUMN IF NOT EXISTS shared_meter_deduction_unit_ids_json TEXT DEFAULT '[]';

CREATE TABLE IF NOT EXISTS rental_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  unit_id INTEGER NOT NULL REFERENCES rental_units(id) ON DELETE CASCADE,
  billing_period TEXT NOT NULL,
  base_rent DOUBLE PRECISION NOT NULL DEFAULT 0,
  water_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
  electricity_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
  actual_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'overdue')),
  paid_date TEXT,
  invoice_ref TEXT,
  receipt_ref TEXT,
  receipt_image_path TEXT,
  invoice_sent_at TEXT,
  receipt_sent_at TEXT,
  paid_at TEXT,
  custom_invoice_note TEXT,
  custom_receipt_note TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  amount_paid DOUBLE PRECISION NOT NULL DEFAULT 0,
  water_period_from TEXT,
  water_period_to TEXT,
  electricity_period_from TEXT,
  electricity_period_to TEXT,
  base_rent_period_from TEXT,
  base_rent_period_to TEXT,
  electricity_meter_json TEXT,
  water_meter_json TEXT,
  UNIQUE (user_id, unit_id, billing_period)
);

-- Utility meter reading rounds (水電錶紀錄)
CREATE TABLE IF NOT EXISTS utility_meter_rounds (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reading_date TEXT NOT NULL,
  period TEXT NOT NULL,
  notes TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS utility_meter_round_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_id INTEGER NOT NULL REFERENCES utility_meter_rounds(id) ON DELETE CASCADE,
  meter_key TEXT NOT NULL,
  reading_value DOUBLE PRECISION,
  photo_path TEXT,
  ocr_text TEXT,
  synced_record_id INTEGER REFERENCES rental_records(id) ON DELETE SET NULL,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (round_id, meter_key)
);

CREATE TABLE IF NOT EXISTS rental_payment_receipts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rent_record_id INTEGER NOT NULL REFERENCES rental_records(id) ON DELETE CASCADE,
  image_path TEXT NOT NULL,
  extracted_method TEXT,
  extracted_transfer_date TEXT,
  extracted_receiving_account TEXT,
  extracted_amount DOUBLE PRECISION,
  extraction_source TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS rental_activity_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  unit_id INTEGER NOT NULL REFERENCES rental_units(id) ON DELETE CASCADE,
  rent_record_id INTEGER,
  action TEXT NOT NULL,
  note TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS rental_charge_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  unit_id INTEGER NOT NULL REFERENCES rental_units(id) ON DELETE CASCADE,
  billing_period TEXT NOT NULL,
  charge_type TEXT NOT NULL CHECK (charge_type IN ('rent', 'water', 'electricity')),
  amount_due DOUBLE PRECISION NOT NULL DEFAULT 0,
  amount_allocated DOUBLE PRECISION NOT NULL DEFAULT 0,
  legacy_record_id INTEGER REFERENCES rental_records(id) ON DELETE SET NULL,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  status TEXT NOT NULL DEFAULT 'unpaid',
  tenant_id INTEGER REFERENCES rental_tenants(id),
  UNIQUE (user_id, unit_id, billing_period, charge_type)
);

CREATE TABLE IF NOT EXISTS rental_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tenant_id INTEGER NOT NULL REFERENCES rental_tenants(id) ON DELETE CASCADE,
  payment_date TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  receipt_image_path TEXT,
  method TEXT,
  reference TEXT,
  notes TEXT,
  legacy_receipt_id INTEGER,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS rental_payment_allocations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  payment_id INTEGER NOT NULL REFERENCES rental_payments(id) ON DELETE CASCADE,
  charge_item_id INTEGER NOT NULL REFERENCES rental_charge_items(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS rental_debit_note_seq (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  note_month TEXT NOT NULL,
  last_seq INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, note_month)
);

CREATE TABLE IF NOT EXISTS rental_debit_note_styles (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_key TEXT NOT NULL,
  styles_json TEXT NOT NULL,
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (user_id, company_key)
);

CREATE TABLE IF NOT EXISTS rental_leases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  unit_id INTEGER NOT NULL REFERENCES rental_units(id) ON DELETE CASCADE,
  tenant_id INTEGER REFERENCES rental_tenants(id) ON DELETE SET NULL,
  tenant_name TEXT NOT NULL,
  tenant_phone TEXT,
  tenant_email TEXT,
  lease_start_date TEXT NOT NULL,
  lease_end_date TEXT NOT NULL,
  actual_end_date TEXT,
  base_rent DOUBLE PRECISION NOT NULL DEFAULT 0,
  due_date_day INTEGER NOT NULL DEFAULT 1,
  deposit_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  deposit_refund DOUBLE PRECISION,
  deposit_deductions DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active',
  end_reason TEXT,
  end_notes TEXT,
  auto_send_receipt_email INTEGER NOT NULL DEFAULT 0,
  automation_enabled INTEGER NOT NULL DEFAULT 1,
  is_current INTEGER NOT NULL DEFAULT 1,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

-- Circular FK: rental_units.current_lease_id → rental_leases(id)
DO $$ BEGIN
  ALTER TABLE rental_units
    ADD CONSTRAINT rental_units_current_lease_id_fkey
    FOREIGN KEY (current_lease_id) REFERENCES rental_leases(id);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS rental_lease_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lease_id INTEGER NOT NULL REFERENCES rental_leases(id) ON DELETE CASCADE,
  doc_type TEXT NOT NULL DEFAULT 'agreement',
  file_path TEXT NOT NULL,
  label TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS rental_document_templates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  template_key TEXT NOT NULL,
  name TEXT NOT NULL,
  payment_instructions TEXT NOT NULL DEFAULT '',
  footer_remark TEXT NOT NULL DEFAULT '',
  rent_invoice_note TEXT NOT NULL DEFAULT '',
  company_json TEXT,
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (user_id, template_key)
);

CREATE TABLE IF NOT EXISTS reconciliation_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  order_no TEXT,
  order_id INTEGER REFERENCES orders(id) ON DELETE SET NULL,
  invoice_id INTEGER REFERENCES invoices(id) ON DELETE SET NULL,
  deposit_time TEXT NOT NULL,
  gross_amount DOUBLE PRECISION NOT NULL,
  payment_method TEXT NOT NULL CHECK (payment_method IN ('Yedpay', 'FPS', 'Payme', '現金', '支票', '銀行轉帳')),
  status TEXT NOT NULL DEFAULT 'Unmatched' CHECK (status IN ('Unmatched', 'Pending Approval', 'Matched', 'Discrepancy')),
  transaction_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
  net_amount DOUBLE PRECISION NOT NULL,
  remarks TEXT,
  receipt_path TEXT,
  source TEXT NOT NULL CHECK (source IN ('yedpay', 'bank_upload', 'manual')),
  external_id TEXT,
  matched_at TEXT,
  confidence TEXT CHECK (confidence IS NULL OR confidence IN ('high', 'medium')),
  suggested_order_id INTEGER REFERENCES orders(id) ON DELETE SET NULL,
  suggested_invoice_id INTEGER REFERENCES invoices(id) ON DELETE SET NULL,
  candidate_order_ids_json TEXT,
  approved_by TEXT,
  approved_at TEXT,
  created_by TEXT,
  created_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

ALTER TABLE reconciliation_records ADD COLUMN IF NOT EXISTS confidence TEXT;
ALTER TABLE reconciliation_records ADD COLUMN IF NOT EXISTS suggested_order_id INTEGER;
ALTER TABLE reconciliation_records ADD COLUMN IF NOT EXISTS suggested_invoice_id INTEGER;
ALTER TABLE reconciliation_records ADD COLUMN IF NOT EXISTS candidate_order_ids_json TEXT;
ALTER TABLE reconciliation_records ADD COLUMN IF NOT EXISTS approved_by TEXT;
ALTER TABLE reconciliation_records ADD COLUMN IF NOT EXISTS approved_at TEXT;
ALTER TABLE reconciliation_records ADD COLUMN IF NOT EXISTS receipt_path TEXT;
ALTER TABLE reconciliation_records ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE reconciliation_records ADD COLUMN IF NOT EXISTS payment_slot INTEGER;

CREATE TABLE IF NOT EXISTS integration_tokens (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  realm_id TEXT,
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (user_id, provider)
);

CREATE TABLE IF NOT EXISTS hub_order_sequences (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  next_serial INTEGER NOT NULL DEFAULT 1001,
  PRIMARY KEY (user_id, platform)
);

CREATE TABLE IF NOT EXISTS integration_sync_state (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  store_key TEXT NOT NULL,
  last_synced_at TEXT,
  PRIMARY KEY (user_id, provider, store_key)
);

CREATE TABLE IF NOT EXISTS integration_settings (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  settings_json TEXT NOT NULL DEFAULT '{}',
  updated_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS deleted_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  label TEXT NOT NULL,
  summary TEXT,
  payload TEXT NOT NULL,
  deleted_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS')),
  expires_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_migrations (
  key TEXT PRIMARY KEY,
  applied_at TEXT DEFAULT (to_char(NOW() AT TIME ZONE 'Asia/Hong_Kong', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role TEXT NOT NULL,
  section TEXT NOT NULL,
  allowed INTEGER NOT NULL DEFAULT 0,
  access_level TEXT NOT NULL DEFAULT 'none',
  PRIMARY KEY (role, section)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_customers_user ON customers(user_id);
CREATE INDEX IF NOT EXISTS idx_invoices_user ON invoices(user_id);
CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice ON invoice_items(invoice_id);
CREATE INDEX IF NOT EXISTS idx_expenses_user ON expenses(user_id);
CREATE INDEX IF NOT EXISTS idx_expenses_user_paid ON expenses(user_id, paid_date DESC);
CREATE INDEX IF NOT EXISTS idx_expenses_user_created_by ON expenses(user_id, created_by_user_id);

CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_kitchen_type ON orders(user_id, order_type)
  WHERE order_type IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_quotation ON orders(quotation_id) WHERE quotation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_order_files_order ON order_files(order_id);

CREATE INDEX IF NOT EXISTS idx_activity_logs_entity ON activity_logs(entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_invoice_files_invoice ON invoice_files(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoices_order_id ON invoices(order_id) WHERE order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_invoices_quotation ON invoices(quotation_id) WHERE quotation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_invoices_user_status ON invoices(user_id, status);
CREATE INDEX IF NOT EXISTS idx_invoices_user_status_due ON invoices(user_id, status, due_date);

CREATE INDEX IF NOT EXISTS idx_quotations_user ON quotations(user_id);
CREATE INDEX IF NOT EXISTS idx_quotation_items_quotation ON quotation_items(quotation_id);
CREATE INDEX IF NOT EXISTS idx_quotation_files_quotation ON quotation_files(quotation_id);

CREATE INDEX IF NOT EXISTS idx_other_income_user ON other_income(user_id);

CREATE INDEX IF NOT EXISTS idx_kitchen_gift_boxes_user ON kitchen_gift_boxes(user_id);
CREATE INDEX IF NOT EXISTS idx_kitchen_movements_user ON kitchen_movements(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kitchen_fulfillments_order ON kitchen_order_fulfillments(user_id, order_id);

CREATE INDEX IF NOT EXISTS idx_kitchen_prep_user ON kitchen_prep_orders(user_id);
CREATE INDEX IF NOT EXISTS idx_kitchen_prep_date ON kitchen_prep_orders(user_id, stewing_date);

CREATE INDEX IF NOT EXISTS idx_stock_items_user ON stock_items(user_id);

CREATE INDEX IF NOT EXISTS idx_inbound_shipments_user ON inbound_shipments(user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_expenses_user_receipt_no ON expenses(user_id, receipt_no);

CREATE INDEX IF NOT EXISTS idx_expense_receipts_expense ON expense_receipts(expense_id);
CREATE INDEX IF NOT EXISTS idx_expense_options_user ON expense_options(user_id, type);

CREATE INDEX IF NOT EXISTS idx_rental_units_user ON rental_units(user_id);
CREATE INDEX IF NOT EXISTS idx_rental_records_user_period ON rental_records(user_id, billing_period);
CREATE INDEX IF NOT EXISTS idx_rental_records_unit ON rental_records(unit_id);
CREATE INDEX IF NOT EXISTS idx_utility_meter_rounds_user ON utility_meter_rounds(user_id, reading_date DESC);
CREATE INDEX IF NOT EXISTS idx_utility_meter_round_items_round ON utility_meter_round_items(round_id);
CREATE INDEX IF NOT EXISTS idx_rental_receipts_record ON rental_payment_receipts(rent_record_id);
CREATE INDEX IF NOT EXISTS idx_rental_activities_unit ON rental_activity_logs(unit_id);

CREATE INDEX IF NOT EXISTS idx_rental_tenants_user ON rental_tenants(user_id);
CREATE INDEX IF NOT EXISTS idx_rental_charge_items_unit_period ON rental_charge_items(unit_id, billing_period);
CREATE INDEX IF NOT EXISTS idx_rental_charge_items_tenant_lookup ON rental_charge_items(user_id, unit_id);
CREATE INDEX IF NOT EXISTS idx_rental_payments_tenant ON rental_payments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_rental_allocations_payment ON rental_payment_allocations(payment_id);
CREATE INDEX IF NOT EXISTS idx_rental_allocations_charge ON rental_payment_allocations(charge_item_id);
CREATE INDEX IF NOT EXISTS idx_rental_charge_items_tenant ON rental_charge_items(tenant_id);

CREATE INDEX IF NOT EXISTS idx_rental_leases_unit ON rental_leases(unit_id);
CREATE INDEX IF NOT EXISTS idx_rental_leases_current ON rental_leases(unit_id, is_current);
CREATE INDEX IF NOT EXISTS idx_rental_lease_docs_lease ON rental_lease_documents(lease_id);

CREATE INDEX IF NOT EXISTS idx_reconciliation_user ON reconciliation_records(user_id);
CREATE INDEX IF NOT EXISTS idx_reconciliation_status ON reconciliation_records(user_id, status);
CREATE INDEX IF NOT EXISTS idx_reconciliation_deposit ON reconciliation_records(user_id, deposit_time DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_reconciliation_external ON reconciliation_records(user_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_hub_external
  ON orders(user_id, source_platform, original_order_id)
  WHERE original_order_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_system_order_no
  ON orders(user_id, system_order_no)
  WHERE system_order_no IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_invoices_hub_external
  ON invoices(user_id, source_platform, original_order_id)
  WHERE original_order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_deleted_records_user ON deleted_records(user_id);
CREATE INDEX IF NOT EXISTS idx_deleted_records_expires ON deleted_records(expires_at);
